name: env
channels:
  - defaults
dependencies:
  - python=3.9.17
  - pip=23.3.1
  - pip:
      - cvxpy==1.2.0
      - matplotlib==3.4.3
      - numpy==1.22.4
      - scikit-learn==1.0
      - scipy==1.7.1
      - seaborn==0.12.2
      - pyyaml==6.0