root: 'examples/exp_results/exp3/noise_3/data/noise_3'
n_cores: 30
type: 'normal'
params:
  d: 10                                         # ambient dimension
  n: 80                                         # number of subspaces
  r: 1                                          # subspace dimension
  K_vec: [1, 10, 20, 40, 60, 80, 100]           # list of numbers of users per subspace
  m_vec: [8]                                    # list of numbers of comparisons per user
  y_noise: 1                                    # noise level for generating labels, use ~ if None
  approx_subspace_noise: 0.3                    # items do not lie exactly in subspace
  reconst_method: 'huber'                       # {ols, huber}