root: 'examples/exp_results/exp1/data/exp1'
n_cores: 30
type: 'normal'
params:
  d: 10                                         # ambient dimension
  n: 80                                         # number of subspaces
  r: 1                                          # subspace dimension
  K_vec: [1, 5, 10, 20, 30, 40, 50, 60, 70, 80] # list of numbers of users per subspace
  m_vec: [1, 2, 4, 6, 8]                        # list of numbers of comparisons per user
  y_noise: 1                                    # noise level for generating labels, use ~ if None
  loss_fun: 'logistic'                          # loss function for learning subspace metric, logistic or hinge
  loss_param: 1                                 # param if loss_function is logistic
  approx_subspace_noise: 0                      # items do not lie exactly in subspace
  reconst_method: 'huber'                       # {ols, huber}